/*******************************************************************************
 * This file is auto generated by ChainStack, add your biz error codes here
 *
 * FileName : error_code.h
 * Desc     : Define biz error code.
 * History  :
 * License  :
 *******************************************************************************/

#ifndef PLANET_ERRORCODE_H
#define PLANET_ERRORCODE_H

// define your error codes here...
#define DEFAULT_ERROR 1

#endif //PLANET_ERRORCODE_H