/*******************************************************************************
 * This file is auto generated by ChainStack, DO NOT MODIFY
 *
 * FileName : biz_view.hpp
 * Desc     : Define contract biz view.
 * History  :
 * License  :
 *******************************************************************************/

#ifndef CSTACK_LIBS_COMMONS_DEPENDENCY_H
#define CSTACK_LIBS_COMMONS_DEPENDENCY_H

#ifdef MYCHAIN_LIB_MOCK
#include "../mychainlib-mock/contract.h"
#include "../mychainlib-mock/third_party/rapidjson/document.h"
#include "../mychainlib-mock/third_party/rapidjson/stringbuffer.h"
#include "../mychainlib-mock/third_party/rapidjson/writer.h"
#include "../mychainlib-mock/third_party/rapidxml/rapidxml.hpp"
#include "../mychainlib-mock/third_party/rapidxml/rapidxml_print.hpp"
#else
#include <mychainlib/contract.h>
#include <third_party/rapidjson/document.h>
#include <third_party/rapidjson/stringbuffer.h>
#include <third_party/rapidjson/writer.h>
#include <third_party/rapidxml/rapidxml.hpp>
#include <third_party/rapidxml/rapidxml_print.hpp>
#endif

#endif //CSTACK_LIBS_COMMONS_DEPENDENCY_H