/*******************************************************************************
 * This file is auto generated by ChainStack, DO NOT MODIFY
 *
 * FileName : error_code.h
 * Desc     : ChainStack framework error codes.
 * History  :
 * License  :
 *******************************************************************************/

#ifndef CSTACK_LIBS_COMMONS_ERROR_CODE_H
#define CSTACK_LIBS_COMMONS_ERROR_CODE_H

// json decoder error definitions
#define JSON_PARSE_ERROR(code)            "json deserialization fail, error code: "+code
#define JSON_FIELD_MISSING(field)         "json deserialization fail, missing field: "+field
#define JSON_DECODE_ERROR_NOT_ARRAY       "json deserialization fail, json field is not array"
#define JSON_DECODE_ERROR_NOT_MAP         "json deserialization fail, json field is not map"
#define JSON_DECODE_ERROR_NOT_OBJECT      "json deserialization fail, json field is not object"
#define JSON_DECODE_ERROR_NOT_INT8        "json deserialization fail, json field is not int8"
#define JSON_DECODE_ERROR_NOT_UINT8       "json deserialization fail, json field is not uint8"
#define JSON_DECODE_ERROR_NOT_INT16       "json deserialization fail, json field is not int16"
#define JSON_DECODE_ERROR_NOT_UINT16      "json deserialization fail, json field is not uint16"
#define JSON_DECODE_ERROR_NOT_INT32       "json deserialization fail, json field is not int32"
#define JSON_DECODE_ERROR_NOT_UINT32      "json deserialization fail, json field is not uint32"
#define JSON_DECODE_ERROR_NOT_INT64       "json deserialization fail, json field is not int64"
#define JSON_DECODE_ERROR_NOT_UINT64      "json deserialization fail, json field is not uint64"
#define JSON_DECODE_ERROR_NOT_STRING      "json deserialization fail, json field is not string"
#define JSON_DECODE_ERROR_NOT_BOOL        "json deserialization fail, json field is not bool"
#define JSON_DECODE_ERROR_NUMBER_OVERFLOW "json deserialization fail, number value out of bound"

// validation errors
#define VALIDATION_ERROR_OUT_OF_RANGE(field)      "range validation fail, field value or length out of range: "+field
#define VALIDATION_ERROR_VALUE_NOT_EQUAL(field)   "value validation fail, value is not same as expected: "+field
#define VALIDATION_ERROR_SIZE_OUT_OF_RANGE(field) "size validation fail, size is out of range: "+field
#define VALIDATION_ERROR_NOT_CONTAIN(field)       "value validation fail, value does not contain expected content: "+field
#define VALIDATION_ERROR_PREFIX_NOT_MATCH(field)  "value validation fail, value does not start with expected content: "+field
#define VALIDATION_ERROR_SUFFIX_NOT_MATCH(field)  "value validation fail, value does not end with expected content: "+field
#define VALIDATION_ERROR_EMPTY(field)             "value validation fail, value is empty: "+field
#define VALIDATION_ERROR_FIELD_MISSING(field)     "value validation fail, field missing: "+field
#define VALIDATION_ERROR_FIELD_NULL(field)        "value validation fail, field is null: "+field
#define VALIDATION_ERROR_ELEMENT_NULL             "value validation fail, element of array/map is null"

#endif //CSTACK_LIBS_COMMONS_ERROR_CODE_H